name = "Misc"
uuid = "4aeeeee3-a66c-4351-93c8-827aac4056fd"
authors = ["xuestrange <xjz1cumt@163.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
